//export const username = 'kwyktest@gmail.com'
export const username = 'kwykreview@gmail.com'
export const kwykURL = "http://localhost:3001/";
//export const kwykURL = "https://shiny.kwyk.in/";
export const greenColor ="#7bc143";
export const greyColor = "#edeff2";
export const whiteColor = "#ffffff";
export const postURL="http://localhost:3001/input_custom";
//export const postURL="https://shiny.kwyk.in/input_custom";
export const welcomeMessage="You will be given a word. Type as many words (separated by comma) that come to your mind and tap send"
export const tableColors = ['#740000', '#c55b11','#f8aa73', '#b2de83', '#7bc143', '#02b150' ]
